### ISSUE TITLE
Inference Pipeline and Support for Visualization

### ISSUE THREAD

**Issue by PaulSudarshan** [Song-Jingyu/LiRaFusion#3]
Hi,
Could you please provide support for inferencing over samples and visualizing the results in the current framework using trained models? Thanks

**Comment by Song-Jingyu** [comment]
Hi,

Thanks for your interest in this work. For visualization please follow this doc. To visualize radar points it requires some tweaking in the code to load radar points and visualize them in a different color. Unfortunately, I don't have the code for doing so in handy and probably won't be able to find them as it's been a while. The best bet would be writing your own visualizer if you want to visualize radar points. If I can find my script I will update the repository. Thanks!

**Comment by PaulSudarshan** [comment]
> Hi,
> 
> Thanks for your interest in this work. For visualization please follow this doc. To visualize radar points it requires some tweaking in the code to load radar points and visualize them in a different color. Unfortunately, I don't have the code for doing so in handy and probably won't be able to find them as it's been a while. The best bet would be writing your own visualizer if you want to visualize radar points. If I can find my script I will update the repository. Thanks!

![image](https://github.com/user-attachments/assets/e09d0b33-2e79-4654-9c38-d4352f69beb3)

Hi, you have still not attached the doc (link is not available in your comment) to visualize the inference and ground truth. Could you please attach it here?
