### ISSUE TITLE
How to combine 5 radars?

### ISSUE THREAD

**Issue by nsa05605** [Song-Jingyu/LiRaFusion#4]
Hi,
I'm studying LiDAR-Radar fusion 3D object detection now, so I wonder about how to combine 5 radar samples. I read the paper "FUTR3D" which you refer a baseline of your paper, and there was a "We stack points captured by all five radars into a single point cloud". So I just finding how to combine them.
When we use nuScenes dataset for radars, there are 5 radars(FRONT, FRONT_LEFT,RIGHT, BACK_LEFT,RIGHT). And .pkl file contain only 5 sweeps? samples? at each view(e.g. only 5 FRONT-view radar scans). And we just use that .pkl file when we are training. So I can't find any part of combining them. Is that just extract radar feature separately and combine features later?

I will waiting your response. Thank you.

**Comment by Song-Jingyu** [comment]
Hi, thanks for your interest in the paper. This is already handled by the MMDetection3D pipeline. I didn't specifically do anything to combine them as the output is a point cloud with points from multiple radars. I would recommend going through the data loading pipeline if you want to customize this process.

**Comment by nsa05605** [comment]
Thank you for your response. I analyzed the source code and found approximate part that aggregating Radar data.

But, still I have a question. did you convert Radar format .pcd to .bin? Because KITTI or LiDAR of nuScenes are consist of .bin format, so I confuse about that.

Thank you.
