### ISSUE TITLE
Distance based Eval and Inference in BEV

### ISSUE THREAD

**Issue by PaulSudarshan** [Song-Jingyu/LiRaFusion#5]
Hi @Song-Jingyu @JunShao0104 ,

Could you please share how you have performed **distance based evaluation** for your released model? Also kindly share the BEV visualization script of the predictions and ground truth

**Comment by Song-Jingyu** [comment]
Hi,

Please refer to the attached script and make necessary adjustments. Thank you!

[evaluate_distance.zip](https://github.com/user-attachments/files/17808082/evaluate_distance.zip)
