### ISSUE TITLE
inference code file

### ISSUE THREAD

**Issue by didu-dzj** [Song-Jingyu/LiRaFusion#6]
Hi，@Song-Jingyu,
Can you share the inference code for LiDAR and RADAR multimodality to run  self-dataset?
Thanks！

**Comment by Song-Jingyu** [comment]
Do you mean running on your own dataset? You can refer to [this guide](https://mmdetection3d.readthedocs.io/en/dev/tutorials/customize_dataset.html) on how to use your own dataset according to the official guide from MMDetection3D.
